name: docker-debian-13

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/docker-debian-13.yml
      - actions/docker/action.yml
  schedule:
    - cron: "0 6 3 * *"

jobs:
  stage1:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/docker@main
        with:
          VAGRANTFILE: LOCAL
          STABLE: STABLE
          PSTAGE: stage0
          ISTAGE: stage1
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage2:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
    needs: stage1
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/docker@main
        with:
          VAGRANTFILE: LOCAL
          STABLE: STABLE
          PSTAGE: stage1
          ISTAGE: stage2
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage3:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
    needs: stage2
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/docker@main
        with:
          VAGRANTFILE: LOCAL
          STABLE: STABLE
          PSTAGE: stage2
          ISTAGE: stage3
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage4:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
    needs: stage3
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/docker@main
        with:
          VAGRANTFILE: LOCAL
          STABLE: STABLE
          PSTAGE: stage3
          ISTAGE: noninteractive
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}
