name: fedora37

on:
  push:
    branches: [ "main" ]
    paths:
      - Vagrantfile.fedora37
      - .github/workflows/fedora37.yml
  schedule:
    - cron: "0 6 6 * *"

jobs:
  vagrant:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        VAGRANTFILE: [Vagrantfile.fedora37]
        STABLE: [STABLE,UNSTABLE]

    env:
      VAGRANT_VAGRANTFILE: ${{ matrix.VAGRANTFILE }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install pybugz
      run: python -m pip install git+https://github.com/williamh/pybugz.git
    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles( matrix.VAGRANTFILE ) }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    - name: Run vagrant up
      run: vagrant up

    - name: ssh into box after boot
      id: run
      run: ./run.sh ${{ matrix.VAGRANTFILE }} ${{secrets.GENTOO_BUGZILLA_API_KEY }} ${{ matrix.STABLE }}
      continue-on-error: true

    - name: Upload full.log
      uses: actions/upload-artifact@v3
      with:
        name: full_log
        path: full*

    - name: Upload build.log
      uses: actions/upload-artifact@v3
      with:
        name: build_log
        path: build*

    - name: Upload info.log
      uses: actions/upload-artifact@v3
      with:
        name: info_log 
        path: info*
    
    - name: Check on failures
      if: steps.run.outcome != 'success'
      run: exit 1
