name: macos-latest

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/macos-latest.yml
  schedule:
    - cron: "0 6 24 * *"

jobs:
  vagrant:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        VAGRANTFILE: [LOCAL]
        STABLE: [STABLE, UNSTABLE]
    env:
      VAGRANT_VAGRANTFILE: ${{ matrix.VAGRANTFILE }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pybugz
        run: python -m pip install git+https://github.com/williamh/pybugz.git

      - name: run bootstrap
        id: run
        run: unset PKG_CONFIG_PATH && ./run_v1.sh ${{ matrix.VAGRANTFILE }} ${{secrets.GENTOO_BUGZILLA_API_KEY }} ${{ matrix.STABLE }} "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        continue-on-error: true

      - name: Upload full.log
        uses: actions/upload-artifact@v3
        with:
          name: full_log
          path: full*

      - name: Upload build.log
        uses: actions/upload-artifact@v3
        with:
          name: build_log
          path: build*

      - name: Upload info.log
        uses: actions/upload-artifact@v3
        with:
          name: info_log
          path: info*

      - name: Check on failures
        if: steps.run.outcome != 'success'
        run: exit 1
