name: ubuntu-2204

on:
  push:
    branches: ["main"]
    paths:
      - Vagrantfile.ubuntu-2204
      - .github/workflows/ubuntu-2204.yml
  schedule:
    - cron: "0 6 17 * *"

jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/kvm@main
        with:
          VAGRANTFILE: Vagrantfile.ubuntu-2204
          STABLE: STABLE
          PSTAGE: stage0
          ISTAGE: stage1
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage2:
    runs-on: ubuntu-latest
    needs: stage1
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/kvm@main
        with:
          VAGRANTFILE: Vagrantfile.ubuntu-2204
          STABLE: STABLE
          PSTAGE: stage1
          ISTAGE: stage2
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage3:
    runs-on: ubuntu-latest
    needs: stage2
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/kvm@main
        with:
          VAGRANTFILE: Vagrantfile.ubuntu-2204
          STABLE: STABLE
          PSTAGE: stage2
          ISTAGE: stage3
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage4:
    runs-on: ubuntu-latest
    needs: stage3
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/kvm@main
        with:
          VAGRANTFILE: Vagrantfile.ubuntu-2204
          STABLE: STABLE
          PSTAGE: stage3
          ISTAGE: noninteractive
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}
