name: ubuntu-2204

on:
  push:
    branches: ["main"]
    paths:
      - run_v2.sh
      - Vagrantfile.ubuntu-2204
      - .github/workflows/ubuntu-2204.yml
  schedule:
    - cron: "0 6 13 * *"

jobs:
  stage1:
    runs-on: macos-12
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/vagrant@main
        with:
          VAGRANTFILE: Vagrantfile.ubuntu-2204
          STABLE: STABLE
          PSTAGE: stage0
          ISTAGE: stage1
          APIKEY: REPLACE${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage2:
    runs-on: macos-12
    needs: stage1
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/vagrant@main
        with:
          VAGRANTFILE: Vagrantfile.ubuntu-2204
          STABLE: STABLE
          PSTAGE: stage1
          ISTAGE: stage2
          APIKEY: REPLACE${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage3:
    runs-on: macos-12
    needs: stage3
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/vagrant@main
        with:
          VAGRANTFILE: Vagrantfile.ubuntu-2204
          STABLE: STABLE
          PSTAGE: stage2
          ISTAGE: stage3
          APIKEY: REPLACE${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage4:
    runs-on: macos-12
    needs: stage3
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/vagrant@main
        with:
          VAGRANTFILE: Vagrantfile.ubuntu-2204
          STABLE: STABLE
          PSTAGE: stage3
          ISTAGE: stage4
          APIKEY: REPLACE${{ secrets.GENTOO_BUGZILLA_API_KEY }}
