name: ubuntu1804

on:
  push:
    branches: [ "master" ]
    paths:
      - Vagrantfile.ubuntu1804
      - .github/workflows/ubuntu1804.yml
  schedule:
    - cron: "0 6 16 * *"

jobs:
  vagrant:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        VAGRANTFILE: [Vagrantfile.ubuntu1804]

    env:
      VAGRANT_VAGRANTFILE: ${{ matrix.VAGRANTFILE }}

    steps:
    - uses: actions/checkout@v2

    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles( matrix.VAGRANTFILE ) }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    - name: Show Vagrant version
      run: vagrant --version

    - name: Run vagrant up
      run: vagrant up

    - name: ssh into box after boot
      run: vagrant ssh -c 'sudo apt-get update && sudo apt-get install -y build-essential && wget https://gitweb.gentoo.org/repo/proj/prefix.git/plain/scripts/bootstrap-prefix.sh && chmod +x bootstrap-prefix.sh && ./bootstrap-prefix.sh $PWD/gentoo-prefix noninteractive'
