name: ubuntu-1804

on:
  push:
    branches: ["main"]
    paths:
      - Vagrantfile.ubuntu-1804
      - .github/workflows/ubuntu-1804.yml
  schedule:
    - cron: "0 6 11 * *"


jobs:
  stage1:
    runs-on: macos-12
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/vagrant@main
        with:
          VAGRANTFILE: Vagrantfile.ubuntu-1804
          STABLE: STABLE
          PSTAGE: stage0
          ISTAGE: stage1
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage2:
    runs-on: macos-12
    needs: stage1
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/vagrant@main
        with:
          VAGRANTFILE: Vagrantfile.ubuntu-1804
          STABLE: STABLE
          PSTAGE: stage1
          ISTAGE: stage2
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage3:
    runs-on: macos-12
    needs: stage2
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/vagrant@main
        with:
          VAGRANTFILE: Vagrantfile.ubuntu-1804
          STABLE: STABLE
          PSTAGE: stage2
          ISTAGE: stage3
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage4:
    runs-on: macos-12
    needs: stage3
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/vagrant@main
        with:
          VAGRANTFILE: Vagrantfile.ubuntu-1804
          STABLE: STABLE
          PSTAGE: stage3
          ISTAGE: noninteractive
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}
