name: ubuntu2204

on:
  push:
    branches: [ "main" ]
    paths:
      - Vagrantfile.ubuntu2204
      - .github/workflows/ubuntu2204.yml
  schedule:
    - cron: "0 6 17 * *"

jobs:
  vagrant:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        VAGRANTFILE: [Vagrantfile.ubuntu2204]

    env:
      VAGRANT_VAGRANTFILE: ${{ matrix.VAGRANTFILE }}

    steps:
    - uses: actions/checkout@v2

    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles( matrix.VAGRANTFILE ) }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    - name: Show Vagrant version
      run: vagrant --version

    - name: Run vagrant up
      run: vagrant up

    - name: ssh into box after boot
      run: vagrant ssh -c 'sudo apt-get update && sudo apt-get install -y build-essential && wget https://gitweb.gentoo.org/repo/proj/prefix.git/plain/scripts/bootstrap-prefix.sh && chmod +x bootstrap-prefix.sh && ./bootstrap-prefix.sh $PWD/gentoo-prefix noninteractive' > full.log
      continue-on-error: true

    - name: Get faulty ebuild
      run: grep -i -A 1 "Details might be found in the build log:" full.log | tail -n1 | awk '{print $2}' | sed 's/.*portage\/\(.*\)\/temp.*/\1/'

    - name: Get build.log
      run:  vagrant ssh -c "cat $(grep -i -A 1 'Details might be found in the build log:' full.log | tail -n1 | awk '{print $2}')" > build.log

    - name: Upload build.log
      uses: actions/upload-artifact@v3
      with:
        name: build_log
        path: build.log
    
    - name: Upload full.log
      uses: actions/upload-artifact@v3
      with:
        name: full_log
        path: full.log
