name: ubuntu2204

on:
  push:
    branches: [ "main" ]
    paths:
      - Vagrantfile.ubuntu2204
      - .github/workflows/ubuntu2204.yml
  schedule:
    - cron: "0 6 17 * *"

jobs:
  vagrant:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        VAGRANTFILE: [Vagrantfile.ubuntu2204]

    env:
      VAGRANT_VAGRANTFILE: ${{ matrix.VAGRANTFILE }}

    steps:
    - uses: actions/checkout@v2

    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles( matrix.VAGRANTFILE ) }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    - name: Show Vagrant version
      run: vagrant --version

    - name: run bootstrap
      id: run
      run: ./run.sh  ${{ matrix.VAGRANTFILE }}
      continue-on-error: true

    - name: Upload full.log
      uses: actions/upload-artifact@v3
      with:
        name: full_log
        path: full*.log

    - name: Upload build.log
      uses: actions/upload-artifact@v3
      with:
        name: build_log
        path: build*.log
    
    - name: Check on failures
      if: steps.run.outcome != 'success'
      run: exit 1