name: ubuntu-2204-arm64

on:
  push:
    branches: ["main"]
    paths:
      - run.sh
      - Vagrantfile.ubuntu-2204-arm64
      - .github/workflows/ubuntu-2204-arm64.yml
  schedule:
    - cron: "0 6 12 * *"

jobs:
  vagrant:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        VAGRANTFILE: [Vagrantfile.ubuntu-2204-arm64]
        STABLE: [STABLE, UNSTABLE]

    env:
      VAGRANT_VAGRANTFILE: ${{ matrix.VAGRANTFILE }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pybugz
        run: python -m pip install git+https://github.com/williamh/pybugz.git
      - run: brew install qemu
      - run: vagrant plugin install vagrant-qemu
      - run: vagrant up --provider qemu
      
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles( matrix.VAGRANTFILE ) }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: run bootstrap
        id: run
        run: ./run.sh  ${{ matrix.VAGRANTFILE }} ${{secrets.GENTOO_BUGZILLA_API_KEY }} ${{ matrix.STABLE }}
        continue-on-error: true

      - name: Upload full.log
        uses: actions/upload-artifact@v3
        with:
          name: full_log
          path: full*

      - name: Upload build.log
        uses: actions/upload-artifact@v3
        with:
          name: build_log
          path: build*

      - name: Upload info.log
        uses: actions/upload-artifact@v3
        with:
          name: info_log
          path: info*
      - name: Check on failures
        if: steps.run.outcome != 'success'
        run: exit 1
