name: ubuntu-2204-riscv64

on:
  push:
    branches: ["main"]
    paths:
      - Vagrantfile.ubuntu-2204-riscv64
      - .github/workflows/ubuntu-2204-riscv64.yml
  schedule:
    - cron: "0 6 13 * *"

jobs:
  stage1:
    runs-on: macos-12
    env:
      VAGRANT_DEFAULT_PROVIDER: qemu
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/qemu@main
        with:
          VAGRANTFILE: Vagrantfile.ubuntu-2204-riscv64
          STABLE: STABLE
          PSTAGE: stage0
          ISTAGE: stage1
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage2:
    runs-on: macos-12
    needs: stage1
    env:
      VAGRANT_DEFAULT_PROVIDER: qemu
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/qemu@main
        with:
          VAGRANTFILE: Vagrantfile.ubuntu-2204-riscv64
          STABLE: STABLE
          PSTAGE: stage1
          ISTAGE: stage2
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage3:
    runs-on: macos-12
    needs: stage2
    env:
      VAGRANT_DEFAULT_PROVIDER: qemu
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/qemu@main
        with:
          VAGRANTFILE: Vagrantfile.ubuntu-2204-riscv64
          STABLE: STABLE
          PSTAGE: stage2
          ISTAGE: stage3
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage4:
    runs-on: macos-12
    needs: stage3
    env:
      VAGRANT_DEFAULT_PROVIDER: qemu
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/qemu@main
        with:
          VAGRANTFILE: Vagrantfile.ubuntu-2204-riscv64
          STABLE: STABLE
          PSTAGE: stage3
          ISTAGE: noninteractive
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}
