name: vagrant-up

on: [push]

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - run: |
        vagrant --version
        vagrant up
        vagrant ssh -c "echo 'hello world!'"
