name: windows-2022-wsl

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/windows-2022-wsl.yml
  schedule:
    - cron: "0 6 18 * *"

defaults:
    run:
        shell: wsl-bash {0}

jobs:
  vagrant:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        VAGRANTFILE: [LOCAL]
        STABLE: [STABLE, UNSTABLE]

    env:
      VAGRANT_VAGRANTFILE: ${{ matrix.VAGRANTFILE }}

    steps:
      - uses: Vampire/setup-wsl@v2
      - run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y git wget python3 python3-pip build-essential
      - uses: actions/checkout@v2
      - name: Install pybugz
        run: python3 -m pip install git+https://github.com/APN-Pucky/pybugz.git
      - name: fix cariage return
        run: sed -i.bak 's/\r//g' *.sh
      - name: Fix to run as root in wsl
        run: wget https://gitweb.gentoo.org/repo/proj/prefix.git/plain/scripts/bootstrap-prefix.sh && sed -i 's/UID/NOUID/g' bootstrap-prefix.sh 
      - name: run bootstrap
        id: run
        run: ./run.sh ${{ matrix.VAGRANTFILE }} ${{secrets.GENTOO_BUGZILLA_API_KEY }} ${{ matrix.STABLE }} '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        continue-on-error: true

      - name: Upload full.log
        uses: actions/upload-artifact@v3
        with:
          name: full_log
          path: full*

      - name: Upload build.log
        uses: actions/upload-artifact@v3
        with:
          name: build_log
          path: build*

      - name: Upload info.log
        uses: actions/upload-artifact@v3
        with:
          name: info_log
          path: info*

      - name: Check on failures
        if: steps.run.outcome != 'success'
        run: exit 1
