name: windows-2022-cygwin

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/windows-2022-cygwin.yml
  schedule:
    - cron: "0 6 17 * *"


jobs:
  stage1:
    runs-on: windows-2022
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/cygwin@main
        with:
          VAGRANTFILE: LOCAL
          STABLE: STABLE
          PSTAGE: stage0
          ISTAGE: stage1
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage2:
    runs-on: windows-2022
    needs: stage1
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/cygwin@main
        with:
          VAGRANTFILE: LOCAL
          STABLE: STABLE
          PSTAGE: stage1
          ISTAGE: stage2
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage3:
    runs-on: windows-2022
    needs: stage2
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/cygwin@main
        with:
          VAGRANTFILE: LOCAL
          STABLE: STABLE
          PSTAGE: stage2
          ISTAGE: stage3
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}

  stage4:
    runs-on: windows-2022
    needs: stage3
    steps:
      - uses: APN-Pucky/gentoo-prefix-tester/actions/cygwin@main
        with:
          VAGRANTFILE: LOCAL
          STABLE: STABLE
          PSTAGE: stage3
          ISTAGE: noninteractive
          APIKEY: ${{ secrets.GENTOO_BUGZILLA_API_KEY }}
